/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kensakurai' at '16/02/22 23:52' with Gradle 2.3
 *
 * @author kensakurai, @date 16/02/22 23:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
