name: schedule_exec_appinspector
on:
  schedule:
    - cron: '0 4 1 * *'
  workflow_dispatch:
jobs:
  schedule_exec_appinspector:
    runs-on: ubuntu-latest
    name: Schedule ApplicationInspector execution
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/ApplicationInspector-Action@v1
        with:
          output-format: sarif
          arguments: --base-path
      - name: Replace filePath
        run: |
          sed -i 's|/github/workspace/src|src|g' AppInspectorResults.sarif
          sed -i 's|/github/workspace/gradlew.bat|gradlew.bat|g' AppInspectorResults.sarif
      - uses: actions/upload-artifact@v2
        with:
          name: AppInspectorResults
          path: AppInspectorResults.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: AppInspectorResults.sarif
          category: AppInspector
