name: schedule_exec_appinspector
on:
  schedule:
    - cron: '0 4 1 * *'
  workflow_dispatch:
jobs:
  schedule_exec_appinspector:
    runs-on: ubuntu-latest
    name: Schedule ApplicationInspector execution
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/ApplicationInspector-Action@v1
        with:
          output-format: html
      - uses: actions/upload-artifact@v2
        with:
          name: AppInspectorResults
          path: AppInspectorResults.html

