name: schedule_exec_pmd
on:
  schedule:
    - cron: '0 5 1 * *'
  workflow_dispatch:
jobs:
  schedule_exec_pmd:
    runs-on: ubuntu-latest
    name: Schedule PMD execution
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pmd-report.sarif
