on:
  release:
    types:
      - published
jobs:
  send-release-info:  
    runs-on: ubuntu-latest
    steps:
    - name: Get release info and Post Data
      uses: kemsakurai/send-deployment-frequency-action/.github/actions/send-deployment-frequency@main
      with:
        web-hook-url: 'https://httpbin.org/post'
        github-token: ${{ secrets.GITHUB_TOKEN }}
